# media_folder: "public/uploads" # Where media files will be stored
# public_folder: "/uploads" # Where the media files can be accesed from the server
# publish_mode: editorial_workflow # For Drafts

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: image,
          choose_url: false,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD/MM/YYYY",
          time_format: "hh:mm a",
          format: "YYYY-MM-DDTHH:mm:ssZ",
          picker_utc: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Thumbnail",
              name: "thumbnail",
              widget: image,
              choose_url: false,
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Sub-Heading", name: "sub_heading", widget: "string" }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields: [
                { label: "Link Text",name: "linkText", widget: "string" },
                { label: "Link URL", name: "url", widget: "string" },
              ],
          }
          - { label: "Regisration Heading", name: "registrationHeading", widget: "string" }
          - { label: "Regisration text", name: "registrationText", widget: "string" }
          - { label: "Regisration Info", name: "registrationInfo", widget: "string" }
          - {
            label: "quotes",
            name: "quotes",
            widget: "list",
            fields: [
              { label: "Image", name: "Image", widget: image, choose_url: false, },
              { label: "Title", name: "title", widget: "string" },
              { label: "Quote", name: "quote", widget: "markdown" },
            ],
          }

      - file: "content/faqs.md"
        label: "Frequently Asked Questions"
        name: "faqs"
        fields:
          - {
              label: "Thumbnail",
              name: "thumbnail",
              widget: image,
              choose_url: false,
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "FAQs",
              name: "faqs",
              widget: "list",
              fields: [
                { label: "Question", name: "question", widget: "string" },
                { label: "Answer", name: "answer", widget: "string" },
              ],
          }
      - file: "content/virtualkfr.md"
        label: "Virtual KFR"
        name: "virtualkfr"
        fields:
          - {
              label: "Thumbnail",
              name: "thumbnail",
              widget: image,
              choose_url: false,
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/donate.md"
        label: "Donate Us"
        name: "donate"
        fields:
          - {
              label: "Thumbnail",
              name: "thumbnail",
              widget: image,
              choose_url: false,
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/terms.md"
        label: "Terms and Conditions"
        name: "terms"
        fields:
          - {
              label: "Thumbnail",
              name: "thumbnail",
              widget: image,
              choose_url: false,
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
